import { Sparkles, RotateCw } from 'lucide-react';
import type { Exoplanet } from '../hooks/useExoplanets';
import type { HostLikelihoodResult } from '../hooks/useHostLikelihood';
import { useInterpretation, buildPayload } from '../hooks/useInterpretation';

const ACCENT = '#34d399';
const MONO = "'JetBrains Mono', ui-monospace, monospace";

interface Props {
    planet: Exoplanet;
    hostScore?: HostLikelihoodResult | null;
}

export default function InterpretationPanel({ planet, hostScore }: Props) {
    const { mutate, data, isPending, isError, reset } = useInterpretation();

    const run = () => mutate(buildPayload(planet, hostScore));

    return (
        <div style={{ marginTop: 16 }}>
            {!data && !isPending && !isError && (
                <button
                    onClick={run}
                    style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: '10px 14px', borderRadius: 8, cursor: 'pointer', border: `1px solid ${ACCENT}44`, background: `${ACCENT}12`, color: ACCENT, fontFamily: MONO, fontSize: 11, letterSpacing: '0.06em', textTransform: 'uppercase', transition: 'all 0.15s' }}
                >
                    <Sparkles size={13} /> Explain this planet
                </button>
            )}

            {isPending && (
                <div style={{ display: 'flex', alignItems: 'center', gap: 9, padding: '10px 14px', borderRadius: 8, border: '1px solid var(--border)', background: 'rgba(255,255,255,0.03)', fontSize: 12, color: 'var(--muted-foreground)' }}>
                    <div style={{ width: 13, height: 13, border: `2px solid ${ACCENT}33`, borderTopColor: ACCENT, borderRadius: '50%', animation: 'interp-spin 0.8s linear infinite' }} />
                    Reading the data…
                    <style>{`@keyframes interp-spin { to { transform: rotate(360deg); } }`}</style>
                </div>
            )}

            {isError && (
                <div style={{ padding: '10px 14px', borderRadius: 8, border: '1px solid var(--border)', background: 'rgba(255,255,255,0.03)', fontSize: 12, color: 'var(--muted-foreground)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10 }}>
                    <span>Couldn't generate an interpretation.</span>
                    <button onClick={() => { reset(); run(); }} style={{ display: 'flex', alignItems: 'center', gap: 5, background: 'none', border: 'none', color: ACCENT, cursor: 'pointer', fontSize: 12, padding: 0 }}>
                        <RotateCw size={12} /> Retry
                    </button>
                </div>
            )}

            {data && (
                <div style={{ padding: '14px 16px', borderRadius: 10, border: `1px solid ${ACCENT}33`, background: 'rgba(255,255,255,0.03)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontFamily: MONO, fontSize: 10, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--muted-foreground)' }}>
                            <Sparkles size={11} style={{ color: ACCENT }} /> Interpretation
                        </div>
                        <button onClick={() => { reset(); run(); }} aria-label="Regenerate" style={{ background: 'none', border: 'none', color: 'var(--muted-foreground)', cursor: 'pointer', display: 'flex', padding: 2 }}>
                            <RotateCw size={12} />
                        </button>
                    </div>

                    {data.split('\n').filter((p) => p.trim()).map((para, i) => (
                        <p key={i} style={{ margin: i === 0 ? '0 0 10px' : '0 0 10px', fontSize: 12.5, lineHeight: 1.7, color: 'var(--muted-foreground)' }}>
                            {para}
                        </p>
                    ))}

                    <div style={{ marginTop: 4, paddingTop: 10, borderTop: '1px solid var(--border)', fontSize: 10, lineHeight: 1.5, color: 'var(--muted-foreground)', opacity: 0.75 }}>
                        Generated by a language model from the measured values shown above. It has no other
                        information about this planet — but like any language model, it can still be wrong. The
                        archive data is the source of truth.
                    </div>
                </div>
            )}
        </div>
    );
}